def log_error(error):
    with open('error.log', 'a') as file:
        file.write(datetime.datetime.utcnow().isoformat() + ': ' + str(error) + '\n')

try:
    # Some code that may raise an exception
except Exception as e:
    log_error(e)
